### PR TITLE
Make sure to replace the used refresh token with a fresh one

### PR DESCRIPTION
**Pull request by rschildmeijer**

### CODE REVIEW

**Comment by rschildmeijer** [comment]
..the previous refresh token is no longer valid so make sure to update your db with a fresh active one

**Comment by stingalleman** [comment]
@Netlob The `where: user` needs to be `where: { id: user.id }`. I thought this would work but it doesn’t (where I tried it , at least)

**Comment by stingalleman** [comment]
& PR looks good to merge

**Comment by Netlob** [comment]
tgtm, thanks for your contribution @rschildmeijer !

**Comment by Netlob** [comment]
please see https://github.com/Netlob/spotistats-api/pull/3#issue-578592381

**Pull request merged**
